steps:
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch master"
      if [ ! -z "master" -a -d "gcb/environments/master ]; then
        cd terraform/environments/master
        echo "run init"
        terraform init
        echo "run validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply -auto-approve terraform.plan
      else
        for dir in gcb/environments/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init
          terraform validate
          terraform plan || exit 1
          cd ../../
        done
      fi