steps:
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
 
        terraform init
    
        terraform validate

        terraform plan -auto-approve 

        terraform apply -auto-approve 

      
