steps:
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
 
        terraform init
    
        terraform validate

        terraform plan -out terraform.plan
        terraform apply -auto-approve terraform.plan
      
